### ISSUE TITLE
KeyError: 'session_key'

### ISSUE THREAD

**Issue by openmotion** [eclair4151/samsung_encrypted_POC#4]
hello
my model is "the frame" UE55LS003
i executed the command and entered the pin code 
but i have this response : 

 python main.py 
Enter TV Pin: xxxx
STEP 1 step1_url : http://192.168.1.40:8080/ws/pairing?step=1&app_id=com.samsung.companion&device_id=12345&type=1
STEP 1 step1_response : {"auth_data":""}

STEP 2 START
STEP 2 step2_response : {"auth_data":""}

STEP 3 START device_id : 12345
STEP 3 START external_server : https://34.210.190.209:5443
r : {"timestamp":1514291242146,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalArgumentException","message":"No actor were found to execute step#3 for device: 12345","path":"/step3"}
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    enc_key = r.json()['session_key']
KeyError: 'session_key'

**Comment by eclair4151** [comment]
That is an L series tv. This script is only for H and J series TVs
